### ISSUE TITLE
Server doesn't start on a fresh install

### ISSUE THREAD

**Issue by BrentOates** [RA341/dockman#40]
Using the below compose file with a fresh `docker compose up` seems to cause the container to not start the webserver, and gets stuck after connecting to the database.

If I revert back to a tag prior to `v1.1` the server starts, but any image >= `v1.1` and it will not start the server.

```
services:
  dockman:
    image: ghcr.io/ra341/dockman:latest
    restart: unless-stopped
    container_name: dockman
    ports:
      - 8866:8866
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/data/dockman:/config
      - /docker/stacks:/docker/stacks
    environment:
      - DOCKMAN_COMPOSE_ROOT=/docker/stacks
      - DOCKMAN_LOG_VERBOSE=true
      - DOCKMAN_LOG_LEVEL=debug
``` 

Logs:
```
Version        : v2.0.0
Flavour        : Docker
BuildDate      : 2025-07-23 6:17 PM UTC (16 hours ago)
------------------------------------------------------------------------------------------
Branch         : release
CommitInfo     : f13fe8dd270b43b3abb700f79cecb0eeace01ea6
GoVersion      : go1.24.5
------------------------------------------------------------------------------------------
Repo           : https://github.com/RA341/dockman
Branch         : https://github.com/RA341/dockman/tree/f13fe8dd270b43b3abb700f79cecb0eeace01ea6
Commit         : https://github.com/RA341/dockman/commit/release
==========================================================================================
╭──────────────────────────────────────────────── Config ────────────────────────────────────────────────╮
│                                                                                                        │
│  Port:             8866            Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *               Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist            Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.23.0.2      Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  ComposeRoot:      /docker/stacks  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
│  ConfigDir:        /config         Directory to store dockman config       Env: DOCKMAN_CONFIG         │
│  Auth.Enable:      false           Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin           authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^  authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869    Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
│  Updater.PassKey:                  Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
│  Log.Level:        debug           disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
│  Log.Verbose:      true            show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
│                                                                                                        │
│  To modify config, set the respective Env:                                                             │
│                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2025-07-24 10:44:09 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
```

**Comment by RA341** [comment]
Hmm, I tried it with your exact config, and it seems to work fine

Is the config directory created on your machine

Try with a different path maybe

The next step would be checking the git repo, could be a permission issue

**Comment by BrentOates** [comment]
Hmm, thanks for looking!

It seems to happen as long as the value of `DOCKMAN_COMPOSE_ROOT` matches the mounted volume, tried a few different directories and no change 😢 

However, the config directory and database files are populated and there, and have data in them when opening with SQLite browser!

If i remove either the environment, or remove the volume bind, then it starts as expected. I'll try my hand at go and see if I can dig any deeper 🙏🏻

**Comment by RA341** [comment]
Ok so the compose_root thing hints that it's an issue with your git repo, 

try switching to the dev build, I pushed some code to check if any intermediate services are failing

```
image: ghcr.io/ra341/dockman:main
```

this is what I get on my machine

```
 ==========================================================================================
 Version        : v2.0.0
 Flavour        : Docker
 BuildDate      : 2025-07-23 6:17 PM UTC (1 day ago)
 ------------------------------------------------------------------------------------------
 Branch         : release
 CommitInfo     : f13fe8dd270b43b3abb700f79cecb0eeace01ea6
 GoVersion      : go1.24.5
 ------------------------------------------------------------------------------------------
 Repo           : https://github.com/RA341/dockman
 Branch         : https://github.com/RA341/dockman/tree/f13fe8dd270b43b3abb700f79cecb0eeace01ea6
 Commit         : https://github.com/RA341/dockman/commit/release
 ==========================================================================================
 ╭──────────────────────────────────────────────── Config ────────────────────────────────────────────────╮
 │                                                                                                        │
 │  Port:             8866            Port to run the server on               Env: DOCKMAN_PORT           │
 │  AllowedOrigins:   *               Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
 │  UIPath:           dist            Path to frontend files                  Env: DOCKMAN_UI_PATH        │
 │  LocalAddr:        172.31.0.2      Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
 │  ComposeRoot:      /docker/stacks  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
 │  ConfigDir:        /config         Directory to store dockman config       Env: DOCKMAN_CONFIG         │
 │  Auth.Enable:      false           Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
 │  Auth.Username:    admin           authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
 │  Auth.Password:    *REDACTED* ^_^  authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
 │  Updater.Addr:     updater:8869    Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
 │  Updater.PassKey:                  Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
 │  Log.Level:        debug           disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
 │  Log.Verbose:      true            show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
 │                                                                                                        │
 │  To modify config, set the respective Env:                                                             │
 │                                                                                                        │
 ╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯
 2025-07-24 21:33:39 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
 2025-07-24 21:33:39 DBG ../core/internal/git/service.go:72 > empty repo, adding sample compose
 2025-07-24 21:33:39 INF ../core/internal/git/service.go:60 > Created new repository path=/docker/stacks
 2025-07-24 21:33:39 DBG ../core/internal/git/service.go:98 > Staged all changes
 ....
```

**Comment by vidalpascual** [comment]
Same problem here, and main tag doesn't solve the problem. :(

```log
Version        : canary
Flavour        : Docker
BuildDate      : 2025-07-24 9:41 PM UTC (1 day ago)
------------------------------------------------------------------------------------------
Branch         : main
CommitInfo     : f679f53bab3d5fc0a97cf5f8f3e2a887a4536daf
GoVersion      : go1.24.5
------------------------------------------------------------------------------------------
Repo           : https://github.com/RA341/dockman
Branch         : https://github.com/RA341/dockman/tree/f679f53bab3d5fc0a97cf5f8f3e2a887a4536daf
Commit         : https://github.com/RA341/dockman/commit/main
[38;5;111m==========================================================================================
╭──────────────────────────────────────────────── Config ─────────────────────────────────────────────────╮
│                                                                                                         │
│  Port:             8866             Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *                Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist             Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.130.0.3      Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  ComposeRoot:      /volume1/docker  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
│  ConfigDir:        /config          Directory to store dockman config       Env: DOCKMAN_CONFIG         │
│  Auth.Enable:      false            Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin            authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^   authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869     Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
│  Updater.PassKey:                   Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
│  Log.Level:        info             disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
│  Log.Verbose:      false            show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
│                                                                                                         │
│  To modify config, set the respective Env:                                                              │
│                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2025-07-25 23:09:15 INF Connected to database path=/config/dockman.db

**Comment by RA341** [comment]
Is the git repo initialized in /volume/docker

also set your log level to debug and repost your logs

```
- DOCKMAN_LOG_LEVEL=debug
```

**Comment by BrentOates** [comment]
Sorry, had a chance to get back to this.

So, using a completely clean testbed directory, it does run on both main/latest;

```
==========================================================================================
Version        : canary
Flavour        : Docker
BuildDate      : 2025-07-24 9:41 PM UTC (1 day ago)
------------------------------------------------------------------------------------------
Branch         : main
CommitInfo     : f679f53bab3d5fc0a97cf5f8f3e2a887a4536daf
GoVersion      : go1.24.5
------------------------------------------------------------------------------------------
Repo           : https://github.com/RA341/dockman
Branch         : https://github.com/RA341/dockman/tree/f679f53bab3d5fc0a97cf5f8f3e2a887a4536daf
Commit         : https://github.com/RA341/dockman/commit/main
==========================================================================================
╭──────────────────────────────────────────────────── Config ─────────────────────────────────────────────────────╮
│                                                                                                                 │
│  Port:             8866                     Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *                        Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist                     Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.23.0.2               Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  ComposeRoot:      /testbed/docker-compose  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
│  ConfigDir:        /config                  Directory to store dockman config       Env: DOCKMAN_CONFIG         │
│  Auth.Enable:      false                    Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin                    authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^           authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869             Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
│  Updater.PassKey:                           Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
│  Log.Level:        debug                    disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
│  Log.Verbose:      true                     show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
│                                                                                                                 │
│  To modify config, set the respective Env:                                                                      │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2025-07-26 09:39:47 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
2025-07-26 09:39:47 DBG ../core/internal/database/service.go:26 > DB service loaded successfully
2025-07-26 09:39:47 DBG ../core/internal/auth/service.go:20 > Auth service loaded successfully
2025-07-26 09:39:47 DBG ../core/internal/ssh/service.go:36 > SSH service loaded successfully
2025-07-26 09:39:47 DBG ../core/internal/files/service.go:27 > File service loaded successfully
2025-07-26 09:39:47 DBG ../core/internal/git/service.go:73 > empty repo, adding sample compose
2025-07-26 09:39:47 INF ../core/internal/git/service.go:61 > Created new repository path=/testbed/docker-compose
2025-07-26 09:39:47 DBG ../core/internal/git/service.go:99 > Staged all changes
2025-07-26 09:39:47 INF ../core/internal/git/service.go:114 > Successfully created commit with hash hash=aff4baee5e461bd14779446602feb24e1396f9f7
2025-07-26 09:39:47 DBG ../core/internal/git/service.go:34 > Git service loaded successfully
2025-07-26 09:39:47 INF ../core/internal/docker_manager/connection.go:52 > Connected to client ID=7606bd1f-f40c-42a5-a03e-a5507c11dbe6 Kernel=6.1.0-37-amd64 name=sharlayan
2025-07-26 09:39:47 DBG ../core/internal/docker_manager/manager.go:75 > setting default client client=local
2025-07-26 09:39:47 INF ../core/internal/git/service.go:122 > Committing all changes before switching to branch branch=local
2025-07-26 09:39:47 INF ../core/internal/git/service.go:91 > Working directory is clean, no changes to commit
2025-07-26 09:39:47 DBG ../core/internal/git/service.go:130 > Checking if branch exists... branch=local
2025-07-26 09:39:47 INF ../core/internal/git/service.go:149 > Switched to branch... branch=local
2025-07-26 09:39:47 DBG ../core/internal/docker_manager/service.go:45 > Docker manager service loaded successfully
2025-07-26 09:39:47 INF ../core/internal/info/service.go:70 > invalid semver, changelog will not be checked version=canary
2025-07-26 09:39:47 INF ../core/internal/info/service.go:39 > checking version result={"CurrentVersion":{"CreatedAt":"0001-01-01T00:00:00Z","DeletedAt":null,"ID":0,"Read":true,"UpdatedAt":"0001-01-01T00:00:00Z","Version":"canary"},"IsNewVersion":false,"ShouldShowChangelog":false}
2025-07-26 09:39:47 DBG ../core/internal/info/service.go:41 > Info service loaded successfully
2025-07-26 09:39:47 INF ../core/cmd/app.go:50 > Dockman initialized successfully
2025-07-26 09:39:47 INF ../core/cmd/server.go:55 > Starting server... port=8866 url=http://172.23.0.2:8866
```


But going back to a directory with existing stacks in it still gets stuck.
- Cleaned out the existing .git and sample compose from previous runs, cleaned out the data directory for dockman
- /docker/stacks contains directories for each stack, each containing compose.yaml files
- /docker/data contains a dockman directory for storing its config

```
==========================================================================================
Version        : canary
Flavour        : Docker
BuildDate      : 2025-07-24 9:41 PM UTC (1 day ago)
------------------------------------------------------------------------------------------
Branch         : main
CommitInfo     : f679f53bab3d5fc0a97cf5f8f3e2a887a4536daf
GoVersion      : go1.24.5
------------------------------------------------------------------------------------------
Repo           : https://github.com/RA341/dockman
Branch         : https://github.com/RA341/dockman/tree/f679f53bab3d5fc0a97cf5f8f3e2a887a4536daf
Commit         : https://github.com/RA341/dockman/commit/main
==========================================================================================
╭──────────────────────────────────────────────── Config ────────────────────────────────────────────────╮
│                                                                                                        │
│  Port:             8866            Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *               Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist            Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.23.0.2      Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  ComposeRoot:      /docker/stacks  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
│  ConfigDir:        /config         Directory to store dockman config       Env: DOCKMAN_CONFIG         │
│  Auth.Enable:      false           Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin           authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^  authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869    Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
│  Updater.PassKey:                  Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
│  Log.Level:        debug           disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
│  Log.Verbose:      true            show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
│                                                                                                        │
│  To modify config, set the respective Env:                                                             │
│                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2025-07-26 09:45:05 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
2025-07-26 09:45:05 DBG ../core/internal/database/service.go:26 > DB service loaded successfully
2025-07-26 09:45:05 DBG ../core/internal/auth/service.go:20 > Auth service loaded successfully
2025-07-26 09:45:05 DBG ../core/internal/ssh/service.go:36 > SSH service loaded successfully
2025-07-26 09:45:05 DBG ../core/internal/files/service.go:27 > File service loaded successfully
2025-07-26 09:45:05 DBG ../core/internal/git/service.go:73 > empty repo, adding sample compose
2025-07-26 09:45:05 INF ../core/internal/git/service.go:61 > Created new repository path=/docker/stacks
```

I am able to go to the data directory and see the database files are there, and if I go to my stacks directory I can see the newly created .git folder and sample compose files

**Comment by RA341** [comment]
Hey! Really appreciate you taking the time to try things out, that was super helpful. 🙌

I’ve just pushed a potential fix to the main tag. When you get a chance, give it a spin and let me know how it goes!

**Comment by BrentOates** [comment]
No change unfortunately!

```
==========================================================================================
Version        : canary
Flavour        : Docker
BuildDate      : 2025-07-26 3:46 PM UTC (3 hours ago)
------------------------------------------------------------------------------------------
Branch         : main
CommitInfo     : e598fc9616da55ef71d887c96a57cebfee4846d3
GoVersion      : go1.24.5
------------------------------------------------------------------------------------------
Repo           : https://github.com/RA341/dockman
Branch         : https://github.com/RA341/dockman/tree/e598fc9616da55ef71d887c96a57cebfee4846d3
Commit         : https://github.com/RA341/dockman/commit/main
==========================================================================================
╭──────────────────────────────────────────────── Config ────────────────────────────────────────────────╮
│                                                                                                        │
│  Port:             8866            Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *               Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist            Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.23.0.2      Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  ComposeRoot:      /docker/stacks  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
│  ConfigDir:        /config         Directory to store dockman config       Env: DOCKMAN_CONFIG         │
│  Auth.Enable:      false           Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin           authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^  authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869    Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
│  Updater.PassKey:                  Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
│  Log.Level:        debug           disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
│  Log.Verbose:      true            show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
│                                                                                                        │
│  To modify config, set the respective Env:                                                             │
│                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2025-07-26 19:05:14 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
2025-07-26 19:05:14 DBG ../core/internal/database/service.go:26 > DB service loaded successfully
2025-07-26 19:05:14 DBG ../core/internal/auth/service.go:20 > Auth service loaded successfully
2025-07-26 19:05:14 DBG ../core/internal/ssh/service.go:36 > SSH service loaded successfully
2025-07-26 19:05:14 DBG ../core/internal/files/service.go:27 > File service loaded successfully
2025-07-26 19:05:14 INF ../core/internal/git/service.go:75 > Created new repository path=/docker/stacks
```

**Comment by RA341** [comment]
Ok i added some more debug logs, pull main again and let me know

**Comment by BrentOates** [comment]
With latest pull :) 

```
2025-07-26 20:29:53 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
2025-07-26 20:29:53 DBG ../core/internal/database/service.go:26 > DB service loaded successfully
2025-07-26 20:29:53 DBG ../core/internal/auth/service.go:20 > Auth service loaded successfully
2025-07-26 20:29:53 DBG ../core/internal/ssh/service.go:36 > SSH service loaded successfully
2025-07-26 20:29:53 DBG ../core/internal/files/service.go:27 > File service loaded successfully
2025-07-26 20:29:53 INF ../core/internal/git/service.go:75 > Created new repository path=/docker/stacks
2025-07-26 20:29:53 DBG ../core/internal/git/service.go:360 > extracting worktree
2025-07-26 20:29:53 DBG ../core/internal/git/service.go:367 > Executing closure
2025-07-26 20:29:53 DBG ../core/internal/git/service.go:106 > Commiting all files in worktree
2025-07-26 20:29:54 DBG ../core/internal/git/service.go:113 > Got tree status
```

**Comment by RA341** [comment]
Thanks! I've narrowed it down to 2 functions that could be causing the hang. The most likely cause is that your working directory contains either large files or a large number of files, which can cause the staging operation to take much longer than expected - this would explain why I'm unable to reproduce the issue.

I've added a 10-second timeout to prevent the function from hanging indefinitely. Please pull the latest changes and test again. If you hit the timeout, you should see an error message after about 10 seconds.

It would also be helpful to know:
- Approximate number of files in your folder
- Whether you have any particularly large files (>100MB)
- Your operating system and file system type

Let me know how it goes!

**Comment by BrentOates** [comment]
Ahaa, that hit the nail on the head!

So in some of my stack directories, there are volume mounts where a bind mount is needed over a standard docker volume.

I'll move those elsewhere and hopefully all will be sorted!

**Comment by RA341** [comment]
let me know if that was actually the issue so that I can add a proper warning

**Comment by vidalpascual** [comment]
> Is the git repo initialized in /volume/docker
> 
> also set your log level to debug and repost your logs
> 
> ```
> - DOCKMAN_LOG_LEVEL=debug
> ```



I'm using a new folder, completely empty.

```
  dockman:
    image: ghcr.io/ra341/dockman:latest
    container_name: Dockman
    hostname: Dockman
    restart: unless-stopped
    networks:
      - nas
    ports:
      - 8866:8866
    environment:
      - DOCKMAN_COMPOSE_ROOT=/volume1/docker
      - DOCKMAN_LOG_VERBOSE=true
      - DOCKMAN_LOG_LEVEL=debug
    volumes:          
      - /volume1/docker:/volume1/docker
      - /volume1/docker/dockman:/config
      - /var/run/docker.sock:/var/run/docker.sock
```

New logs (it's a loop):

```
[38;5;111m==========================================================================================
                                  
      ___           ___           ___           ___           ___           ___           ___     
     /\  \         /\  \         /\  \         /\__\         /\__\         /\  \         /\__\    
    /::\  \       /::\  \       /::\  \       /:/  /        /::|  |       /::\  \       /::|  |   
   /:/\:\  \     /:/\:\  \     /:/\:\  \     /:/__/        /:|:|  |      /:/\:\  \     /:|:|  |   
  /:/  \:\__\   /:/  \:\  \   /:/  \:\  \   /::\__\____   /:/|:|__|__   /::\~\:\  \   /:/|:|  |__ 
 /:/__/ \:|__| /:/__/ \:\__\ /:/__/ \:\__\ /:/\:::::\__\ /:/ |::::\__\ /:/\:\ \:\__\ /:/ |:| /\__\
 \:\  \ /:/  / \:\  \ /:/  / \:\  \  \/__/ \/_|:|~~|~    \/__/~~/:/  / \/__\:\/:/  / \/__|:|/:/  /
  \:\  /:/  /   \:\  /:/  /   \:\  \          |:|  |           /:/  /       \::/  /      |:/:/  / 
   \:\/:/  /     \:\/:/  /     \:\  \         |:|  |          /:/  /        /:/  /       |::/  /  
    \::/__/       \::/  /       \:\__\        |:|  |         /:/  /        /:/  /        /:/  /   
     ~~            \/__/         \/__/         \|__|         \/__/         \/__/         \/__/
 
[38;5;111m==========================================================================================
Version        : v2.0.0
Flavour        : Docker
BuildDate      : 2025-07-23 6:17 PM UTC (5 days ago)
------------------------------------------------------------------------------------------
Branch         : release
CommitInfo     : f13fe8dd270b43b3abb700f79cecb0eeace01ea6
GoVersion      : go1.24.5
------------------------------------------------------------------------------------------
Repo           : https://github.com/RA341/dockman
Branch         : https://github.com/RA341/dockman/tree/f13fe8dd270b43b3abb700f79cecb0eeace01ea6
Commit         : https://github.com/RA341/dockman/commit/release
[38;5;111m==========================================================================================
╭──────────────────────────────────────────────── Config ─────────────────────────────────────────────────╮
│                                                                                                         │
│  Port:             8866             Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *                Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist             Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.130.0.23     Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  ComposeRoot:      /volume1/docker  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
│  ConfigDir:        /config          Directory to store dockman config       Env: DOCKMAN_CONFIG         │
│  Auth.Enable:      false            Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin            authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^   authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869     Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
│  Updater.PassKey:                   Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
│  Log.Level:        debug            disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
│  Log.Verbose:      true             show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
│                                                                                                         │
│  To modify config, set the respective Env:                                                              │
│                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2025-07-28 19:18:54 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
2025-07-28 19:20:08 FTL ../core/internal/git/service.go:31 > Failed to create commit error="could not stage changes: entry not found"
[38;5;111m==========================================================================================
                                  
      :::::::::   ::::::::   ::::::::  :::    :::   :::   :::       :::     ::::    ::: 
     :+:    :+: :+:    :+: :+:    :+: :+:   :+:   :+:+: :+:+:    :+: :+:   :+:+:   :+:  
    +:+    +:+ +:+    +:+ +:+        +:+  +:+   +:+ +:+:+ +:+  +:+   +:+  :+:+:+  +:+   
   +#+    +:+ +#+    +:+ +#+        +#++:++    +#+  +:+  +#+ +#++:++#++: +#+ +:+ +#+    
  +#+    +#+ +#+    +#+ +#+        +#+  +#+   +#+       +#+ +#+     +#+ +#+  +#+#+#     
 #+#    #+# #+#    #+# #+#    #+# #+#   #+#  #+#       #+# #+#     #+# #+#   #+#+#      
#########   ########   ########  ###    ### ###       ### ###     ### ###    ####
 
[38;5;111m==========================================================================================
Version        : v2.0.0
Flavour        : Docker
BuildDate      : 2025-07-23 6:17 PM UTC (5 days ago)
------------------------------------------------------------------------------------------
Branch         : release
CommitInfo     : f13fe8dd270b43b3abb700f79cecb0eeace01ea6
GoVersion      : go1.24.5
------------------------------------------------------------------------------------------
Repo           : https://github.com/RA341/dockman
Branch         : https://github.com/RA341/dockman/tree/f13fe8dd270b43b3abb700f79cecb0eeace01ea6
Commit         : https://github.com/RA341/dockman/commit/release
[38;5;111m==========================================================================================
╭──────────────────────────────────────────────── Config ─────────────────────────────────────────────────╮
│                                                                                                         │
│  Port:             8866             Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *                Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist             Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.130.0.23     Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  ComposeRoot:      /volume1/docker  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
│  ConfigDir:        /config          Directory to store dockman config       Env: DOCKMAN_CONFIG         │
│  Auth.Enable:      false            Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin            authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^   authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869     Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
│  Updater.PassKey:                   Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
│  Log.Level:        debug            disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
│  Log.Verbose:      true             show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
│                                                                                                         │
│  To modify config, set the respective Env:                                                              │
│                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2025-07-28 19:20:10 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
```

**Comment by RA341** [comment]
You are on release tag, switch to the main tag which contains additional debug logs and a potential fix

```
  dockman:
    image: ghcr.io/ra341/dockman:main # <-- main tag not release
    container_name: Dockman
    hostname: Dockman
    restart: unless-stopped
    networks:
      - nas
    ports:
      - 8866:8866
    environment:
      - DOCKMAN_COMPOSE_ROOT=/volume1/docker
      - DOCKMAN_LOG_VERBOSE=true
      - DOCKMAN_LOG_LEVEL=debug
    volumes:          
      - /volume1/docker:/volume1/docker
      - /volume1/docker/dockman:/config
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by vidalpascual** [comment]
> You are on release tag, switch to the main tag which contains additional debug logs and a potential fix

Sorry about that. Changed to main, but still the same problem:

```
[38;5;111m==========================================================================================
                                  
 ________      ______    ______   __   ___  ___      ___       __      _____  ___   
|"      "\    /    " \  /" _  "\ |/"| /  ")|"  \    /"  |     /""\    (\"   \|"  \  
(.  ___  :)  // ____  \(: ( \___)(: |/   /  \   \  //   |    /    \   |.\\   \    | 
|: \   ) || /  /    ) :)\/ \     |    __/   /\\  \/.    |   /' /\  \  |: \.   \\  | 
(| (___\ ||(: (____/ // //  \ _  (// _  \  |: \.        |  //  __'  \ |.  \    \. | 
|:       :) \        / (:   _) \ |: | \  \ |.  \    /:  | /   /  \\  \|    \    \ | 
(________/   \"_____/   \_______)(__|  \__)|___|\__/|___|(___/    \___)\___|\____\)
 
[38;5;111m==========================================================================================
Version        : canary
Flavour        : Docker
BuildDate      : 2025-07-24 9:41 PM UTC (3 days ago)
------------------------------------------------------------------------------------------
Branch         : main
CommitInfo     : f679f53bab3d5fc0a97cf5f8f3e2a887a4536daf
GoVersion      : go1.24.5
------------------------------------------------------------------------------------------
Repo           : https://github.com/RA341/dockman
Branch         : https://github.com/RA341/dockman/tree/f679f53bab3d5fc0a97cf5f8f3e2a887a4536daf
Commit         : https://github.com/RA341/dockman/commit/main
[38;5;111m==========================================================================================
╭──────────────────────────────────────────────── Config ─────────────────────────────────────────────────╮
│                                                                                                         │
│  Port:             8866             Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *                Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist             Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.130.0.23     Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  ComposeRoot:      /volume1/docker  Root directory for compose files        Env: DOCKMAN_COMPOSE_ROOT   │
│  ConfigDir:        /config          Directory to store dockman config       Env: DOCKMAN_CONFIG         │
│  Auth.Enable:      false            Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin            authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^   authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869     Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
│  Updater.PassKey:                   Authentication key for dockman updater  Env: DOCKMAN_UPDATER_KEY    │
│  Log.Level:        debug            disabled|debug|info|warn|error|fatal    Env: DOCKMAN_LOG_LEVEL      │
│  Log.Verbose:      true             show more info in logs                  Env: DOCKMAN_LOG_VERBOSE    │
│                                                                                                         │
│  To modify config, set the respective Env:                                                              │
│                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2025-07-28 19:31:18 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
2025-07-28 19:31:18 DBG ../core/internal/database/service.go:26 > DB service loaded successfully
2025-07-28 19:31:18 DBG ../core/internal/auth/service.go:20 > Auth service loaded successfully
2025-07-28 19:31:18 DBG ../core/internal/ssh/service.go:36 > SSH service loaded successfully
2025-07-28 19:31:18 DBG ../core/internal/files/service.go:27 > File service loaded successfully
2025-07-28 19:37:07 FTL ../core/internal/git/service.go:31 > Failed to create commit error="could not stage changes: entry not found"
Container started
[38;5;111m==========================================================================================
                                  
      :::::::::   ::::::::   ::::::::  :::    :::   :::   :::       :::     ::::    ::: 
     :+:    :+: :+:    :+: :+:    :+: :+:   :+:   :+:+: :+:+:    :+: :+:   :+:+:   :+:  
    +:+    +:+ +:+    +:+ +:+        +:+  +:+   +:+ +:+:+ +:+  +:+   +:+  :+:+:+  +:+   
   +#+    +:+ +#+    +:+ +#+        +#++:++    +#+  +:+  +#+ +#++:++#++: +#+ +:+ +#+    
  +#+    +#+ +#+    +#+ +#+        +#+  +#+   +#+       +#+ +#+     +#+ +#+  +#+#+#     
Flavour        : Docker
BuildDate      : 2025-07-24 9:41 PM UTC (3 days ago)
------------------------------------------------------------------------------------------
│                                                                                                         │
│  Port:             8866             Port to run the server on               Env: DOCKMAN_PORT           │
│  AllowedOrigins:   *                Allowed origins for the API (in CSV)    Env: DOCKMAN_ORIGINS        │
│  UIPath:           dist             Path to frontend files                  Env: DOCKMAN_UI_PATH        │
│  LocalAddr:        172.130.0.23     Local machine IP address                Env: DOCKMAN_MACHINE_ADDR   │
│  Auth.Enable:      false            Enable authentication                   Env: DOCKMAN_AUTH_ENABLE    │
│  Auth.Username:    admin            authentication username                 Env: DOCKMAN_AUTH_USERNAME  │
│  Auth.Password:    *REDACTED* ^_^   authentication password                 Env: DOCKMAN_AUTH_PASSWORD  │
│  Updater.Addr:     updater:8869     Host address for dockman updater        Env: DOCKMAN_UPDATER_HOST   │
2025-07-28 19:37:09 INF ../core/internal/database/connect.go:52 > Connected to database path=/config/dockman.db
2025-07-28 19:37:09 DBG ../core/internal/database/service.go:26 > DB service loaded successfully
2025-07-28 19:37:09 DBG ../core/internal/auth/service.go:20 > Auth service loaded successfully
2025-07-28 19:37:09 DBG ../core/internal/ssh/service.go:36 > SSH service loaded successfully
2025-07-28 19:37:09 DBG ../core/internal/files/service.go:27 > File service loaded successfully
```

**Comment by RA341** [comment]
You're on a slightly outdated version the latest build was pushed just yesterday.

To update, run:

```
docker pull ghcr.io/ra341/dockman:main
```

The latest commit hash is:

```
f7cb0f89139c11d7227c685bb1636015fa762237
```

**Comment by vidalpascual** [comment]
> You're on a slightly outdated version the latest build was pushed just yesterday.
> 
> To update, run:
> 
> ```
> docker pull ghcr.io/ra341/dockman:main
> ```
> 
> The latest commit hash is:
> 
> ```
> f7cb0f89139c11d7227c685bb1636015fa762237
> ```

Updated. I think the problem it's that my docker-compose.yml file is in a folder within the working directories of the other containers. I thought Dockman only scans folder first level, but it scans all the folders recursively. I get this log at the end of the starting/scanning process:

```2025-07-28 20:52:47 DBG ../core/internal/git/service.go:127 > Working directory is not clean```

If I move my docker-compose.yml file to other empty folder, this last version of Dockman starts and works fine. But that it's not the location I want for my file. Maybe and env variable for this?

**Comment by BrentOates** [comment]
@RA341 Yup, as @vidalpascual says, it was due to some of the data directories I had alongside stack files and it trying to traverse them all. 

Once I moved them to their own higher level data directory the app started fine.

I did try get an ignore file working to have git only care about the top level compose and files at that level but ended up doing more damage than good!

**Comment by RA341** [comment]
Thanks a lot, I've added proper error handling and tests

Appreciate you all taking the time to dig into the issue and test things out, your input was super helpful!

**Comment by cirrusflyer** [comment]
Is there a reason why, when creating a new Compose Directory via the GUI, that the default compose file name created isn't:

compose.yaml

OR

docker-compose.yml
